"""
services/schema_healer/healer/llm_client.py

LIVE-TEST FIX (2026-09-22): see SCHEMA_HEALER_LIVE_TEST_REPORT.md. The live
run against a real Ollama + phi4-mini showed `{"op": "rename_field"}` with
no `source`/`target` passing the old hand-written `_RESPONSE_SCHEMA` (which
only required `op`) and then being correctly rejected downstream by
`mapping_ops.parse_ops` — the fail-safe worked, but the schema Ollama
decoded against and the schema the response was actually checked against
had drifted apart, so most attempts were failing for a fixable reason.

Two changes:

1. Ollama receives a flat JSON schema because its grammar constraint does
    not reliably support the `oneOf`/`$ref` schema generated by the
    discriminated Pydantic union. The response is still validated against
    `HealingLLMResponse`, which remains the strict safety boundary.
2. The response is now validated with `HealingLLMResponse.model_validate_json()`
   inside `_call_model` itself, not just downstream in `parse_ops`. A
   response that satisfies the JSON *type* shape but violates the pydantic
   model (missing an op-specific field, exactly the observed failure) is
   now treated the same as an HTTP or JSON-decode failure: it makes
   `_call_model` return `None`, which triggers the one-shot fallback-model
   retry in `propose_mapping`. Previously only transport-level failures
   got a retry; a structurally-present-but-incomplete op went straight
   through as a "successful" call and was only caught one layer down.
   `mapping_ops.parse_ops` remains the actual safety boundary — this
   client still hands back plain dicts, never trusts its own validation as
   a reason to skip that layer (see the report's explicit warning: "Do not
   bypass parse_ops").

Calls Ollama directly, not through `llm-gateway`, for the same documented
reason as `rca_copilot/rca/llm_client.py`: the gateway's exact contract
wasn't available to confirm from this environment.
"""
from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from typing import Any

import httpx
from pydantic import ValidationError

from .mapping_ops import HealingLLMResponse

logger = logging.getLogger("schema_healer.llm_client")

_OLLAMA_FORMAT_SCHEMA = {
    "type": "object",
    "properties": {
        "ops": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "op": {
                        "type": "string",
                        "enum": ["rename_field", "cast_type", "set_default", "drop_field", "const_map"],
                    },
                    "source": {"type": "string"},
                    "target": {"type": "string"},
                    "field": {"type": "string"},
                    "target_type": {"type": "string"},
                    "value": {"type": "string"},
                    "mapping": {"type": "object"},
                    "fallback": {"type": "string"},
                },
                "required": ["op"],
            },
        },
        "root_cause_category": {
            "type": "string",
            "enum": [
                "field_renamed",
                "new_optional_field",
                "new_required_field",
                "field_removed",
                "type_widened",
                "type_narrowed",
                "enum_value_added",
                "unknown",
            ],
        },
        "confidence": {"type": "number", "minimum": 0, "maximum": 1},
        "narrative": {"type": "string"},
    },
    "required": ["ops", "confidence"],
}

# Ollama's own docs tip: passing the schema as a string in the prompt too
# (not just the `format` field) grounds smaller/quantized models better.
# This is a plain-text cheat-sheet of exactly the fields each op needs,
# aimed directly at the observed failure mode (a bare {"op": "rename_field"}
# with nothing else) rather than relying on grammar constraints alone.
_OP_FIELD_REFERENCE = """\
Each op object MUST include every field shown for its type — never just "op" alone:
  {"op": "rename_field", "source": "<old field name>", "target": "<new field name>"}
  {"op": "cast_type", "field": "<field name>", "target_type": "string"|"integer"|"float"|"boolean"}
  {"op": "set_default", "field": "<field name>", "value": <default value>}
  {"op": "drop_field", "field": "<field name>"}
  {"op": "const_map", "field": "<field name>", "mapping": {"<old value>": "<new value>"}, "fallback": <value>}
"""

FAIL_SAFE_PLACEHOLDER: dict[str, Any] = {
    "ops": [],
    "root_cause_category": "unknown",
    "narrative": "LLM call failed (all models exhausted); no mapping proposed.",
    "confidence": 0.0,
}


@dataclass
class LLMHealingProposal:
    ops: list[dict]
    root_cause_category: str
    narrative: str
    confidence: float
    model_used: str | None


def _build_prompt(contract_yaml_text: str, record: dict, diagnostic_text: str) -> str:
    return (
        "A JSON record failed validation against a data contract in a streaming "
        "pipeline. Propose a mapping to heal it, using ONLY the operation "
        "vocabulary below. Do not write code or prose transformations — "
        "only ops from this closed list, and every op must carry all of its "
        "required fields, not just its name. Return exactly one JSON object "
        "with top-level keys ops, root_cause_category, narrative, and confidence. "
        "root_cause_category must be one of field_renamed, new_optional_field, "
        "new_required_field, field_removed, type_widened, type_narrowed, "
        "enum_value_added, or unknown; "
        "do not return a single operation object or Markdown. If you cannot "
        "confidently fix it, return an empty ops list and confidence 0.\n\n"
        f"--- Operation vocabulary (all fields required per op) ---\n{_OP_FIELD_REFERENCE}\n"
        f"--- Data contract (YAML) ---\n{contract_yaml_text}\n\n"
        f"--- Validation errors ---\n{diagnostic_text}\n\n"
        f"--- Offending record (JSON) ---\n{json.dumps(record)}\n"
    )


class OllamaHealerClient:
    def __init__(
        self,
        base_url: str,
        model: str,
        fallback_model: str,
        timeout_seconds: float = 60.0,
    ):
        self.base_url = base_url.rstrip("/")
        self.model = model
        self.fallback_model = fallback_model
        self.timeout_seconds = timeout_seconds

    def _call_model(self, model: str, prompt: str) -> HealingLLMResponse | None:
        try:
            resp = httpx.post(
                f"{self.base_url}/api/chat",
                json={
                    "model": model,
                    "messages": [{"role": "user", "content": prompt}],
                    "stream": False,
                    "format": _OLLAMA_FORMAT_SCHEMA,
                },
                timeout=self.timeout_seconds,
            )
            resp.raise_for_status()
            content = resp.json()["message"]["content"]
            return HealingLLMResponse.model_validate_json(content)
        except (httpx.HTTPError, KeyError, json.JSONDecodeError, ValidationError) as e:
            # ValidationError here is the fix: a response that's valid JSON
            # but has an incomplete op (the exact bug the live test found)
            # now counts as a failed call and earns a fallback-model retry,
            # instead of silently becoming a "successful" proposal that
            # only gets caught one layer down in parse_ops.
            logger.warning("schema_healer LLM call to model=%s failed: %s", model, e)
            return None

    def propose_mapping(
        self, contract_yaml_text: str, record: dict, diagnostic_text: str
    ) -> LLMHealingProposal:
        prompt = _build_prompt(contract_yaml_text, record, diagnostic_text)

        result = self._call_model(self.model, prompt)
        model_used = self.model
        if result is None and self.fallback_model and self.fallback_model != self.model:
            logger.info("schema_healer falling back to model=%s", self.fallback_model)
            result = self._call_model(self.fallback_model, prompt)
            model_used = self.fallback_model

        if result is None:
            return LLMHealingProposal(**FAIL_SAFE_PLACEHOLDER, model_used=None)

        return LLMHealingProposal(
            ops=[op.model_dump() for op in result.ops],
            root_cause_category=result.root_cause_category,
            narrative=result.narrative,
            confidence=result.confidence,
            model_used=model_used,
        )
